shoulder_pan_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: shoulder_pan_joint
    joint_speed: 0.5
    motor:
        id: 1
        init: 512
        min: 0
        max: 1023

shoulder_pitch_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller_dual_motor
        type: JointPositionControllerDual
    joint_name: shoulder_pitch_joint
    joint_speed: 0.5
    motor_master:
        id: 2
        init: 512
        min: 1023
        max: 0
    motor_slave:
        id: 3
        calibration_offset: -10

elbow_flex_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller_dual_motor
        type: JointPositionControllerDual
    joint_name: elbow_flex_joint
    joint_speed: 0.5
    motor_master:
        id: 4
        init: 512
        min: 1023
        max: 0
    motor_slave:
        id: 5
        calibration_offset: 0

wrist_roll_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: wrist_roll_joint
    joint_speed: 0.5
    motor:
        id: 6
        init: 512
        min: 0
        max: 1023
