//#line 2 "/opt/ros/groovy/share/dynamic_reconfigure/templates/ConfigType.h"
// *********************************************************
// 
// File autogenerated for the hearbo_cart_msgs package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

/***********************************************************
 * Software License Agreement (BSD License)
 *
 *  Copyright (c) 2008, Willow Garage, Inc.
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name of the Willow Garage nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 ***********************************************************/

// Author: Blaise Gassend


#ifndef __hearbo_cart_msgs__CARTCOMMANDCONFIG_H__
#define __hearbo_cart_msgs__CARTCOMMANDCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace hearbo_cart_msgs
{
  class CartCommandConfigStatics;
  
  class CartCommandConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(CartCommandConfig &config, const CartCommandConfig &max, const CartCommandConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const CartCommandConfig &config1, const CartCommandConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, CartCommandConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const CartCommandConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, CartCommandConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const CartCommandConfig &config) const = 0;
      virtual void getValue(const CartCommandConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T CartCommandConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (CartCommandConfig::* field);

      virtual void clamp(CartCommandConfig &config, const CartCommandConfig &max, const CartCommandConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const CartCommandConfig &config1, const CartCommandConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, CartCommandConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const CartCommandConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, CartCommandConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const CartCommandConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const CartCommandConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, CartCommandConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); i++)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string name, std::string type, int parent, int id, bool s, T PT::* f) : AbstractGroupDescription(name, type, parent, id, s), field(f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;
        
        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++) 
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }
      
      virtual void updateParams(boost::any &cfg, CartCommandConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++) 
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<CartCommandConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(CartCommandConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = params.begin(); i != params.end(); i++)
      {
        boost::any val;
        (*i)->getValue(config, val);

        if("publish_flag"==(*i)->name){publish_flag = boost::any_cast<bool>(val);}
        if("drive_flag"==(*i)->name){drive_flag = boost::any_cast<bool>(val);}
        if("drive_mode"==(*i)->name){drive_mode = boost::any_cast<int>(val);}
        if("drive_id_0"==(*i)->name){drive_id_0 = boost::any_cast<bool>(val);}
        if("drive_id_1"==(*i)->name){drive_id_1 = boost::any_cast<bool>(val);}
        if("drive_id_2"==(*i)->name){drive_id_2 = boost::any_cast<bool>(val);}
        if("drive_id_3"==(*i)->name){drive_id_3 = boost::any_cast<bool>(val);}
        if("each_vel_0"==(*i)->name){each_vel_0 = boost::any_cast<double>(val);}
        if("each_vel_1"==(*i)->name){each_vel_1 = boost::any_cast<double>(val);}
        if("each_vel_2"==(*i)->name){each_vel_2 = boost::any_cast<double>(val);}
        if("each_vel_3"==(*i)->name){each_vel_3 = boost::any_cast<double>(val);}
        if("each_ang_0"==(*i)->name){each_ang_0 = boost::any_cast<double>(val);}
        if("each_ang_1"==(*i)->name){each_ang_1 = boost::any_cast<double>(val);}
        if("each_ang_2"==(*i)->name){each_ang_2 = boost::any_cast<double>(val);}
        if("each_ang_3"==(*i)->name){each_ang_3 = boost::any_cast<double>(val);}
        if("all_vel"==(*i)->name){all_vel = boost::any_cast<double>(val);}
        if("all_ang"==(*i)->name){all_ang = boost::any_cast<double>(val);}
        if("gain_flag"==(*i)->name){gain_flag = boost::any_cast<bool>(val);}
        if("gain_id_ch0_0"==(*i)->name){gain_id_ch0_0 = boost::any_cast<bool>(val);}
        if("gain_id_ch0_1"==(*i)->name){gain_id_ch0_1 = boost::any_cast<bool>(val);}
        if("gain_id_ch0_2"==(*i)->name){gain_id_ch0_2 = boost::any_cast<bool>(val);}
        if("gain_id_ch0_3"==(*i)->name){gain_id_ch0_3 = boost::any_cast<bool>(val);}
        if("gain_ch0_0"==(*i)->name){gain_ch0_0 = boost::any_cast<int>(val);}
        if("gain_ch0_1"==(*i)->name){gain_ch0_1 = boost::any_cast<int>(val);}
        if("gain_ch0_2"==(*i)->name){gain_ch0_2 = boost::any_cast<int>(val);}
        if("gain_ch0_3"==(*i)->name){gain_ch0_3 = boost::any_cast<int>(val);}
        if("gain_id_ch1_0"==(*i)->name){gain_id_ch1_0 = boost::any_cast<bool>(val);}
        if("gain_id_ch1_1"==(*i)->name){gain_id_ch1_1 = boost::any_cast<bool>(val);}
        if("gain_id_ch1_2"==(*i)->name){gain_id_ch1_2 = boost::any_cast<bool>(val);}
        if("gain_id_ch1_3"==(*i)->name){gain_id_ch1_3 = boost::any_cast<bool>(val);}
        if("gain_ch1_0"==(*i)->name){gain_ch1_0 = boost::any_cast<int>(val);}
        if("gain_ch1_1"==(*i)->name){gain_ch1_1 = boost::any_cast<int>(val);}
        if("gain_ch1_2"==(*i)->name){gain_ch1_2 = boost::any_cast<int>(val);}
        if("gain_ch1_3"==(*i)->name){gain_ch1_3 = boost::any_cast<int>(val);}
        if("encoder_flag"==(*i)->name){encoder_flag = boost::any_cast<bool>(val);}
        if("encoder_id_ch0_0"==(*i)->name){encoder_id_ch0_0 = boost::any_cast<bool>(val);}
        if("encoder_id_ch0_1"==(*i)->name){encoder_id_ch0_1 = boost::any_cast<bool>(val);}
        if("encoder_id_ch0_2"==(*i)->name){encoder_id_ch0_2 = boost::any_cast<bool>(val);}
        if("encoder_id_ch0_3"==(*i)->name){encoder_id_ch0_3 = boost::any_cast<bool>(val);}
        if("encoder_ch0_0"==(*i)->name){encoder_ch0_0 = boost::any_cast<int>(val);}
        if("encoder_ch0_1"==(*i)->name){encoder_ch0_1 = boost::any_cast<int>(val);}
        if("encoder_ch0_2"==(*i)->name){encoder_ch0_2 = boost::any_cast<int>(val);}
        if("encoder_ch0_3"==(*i)->name){encoder_ch0_3 = boost::any_cast<int>(val);}
        if("encoder_id_ch1_0"==(*i)->name){encoder_id_ch1_0 = boost::any_cast<bool>(val);}
        if("encoder_id_ch1_1"==(*i)->name){encoder_id_ch1_1 = boost::any_cast<bool>(val);}
        if("encoder_id_ch1_2"==(*i)->name){encoder_id_ch1_2 = boost::any_cast<bool>(val);}
        if("encoder_id_ch1_3"==(*i)->name){encoder_id_ch1_3 = boost::any_cast<bool>(val);}
        if("encoder_ch1_0"==(*i)->name){encoder_ch1_0 = boost::any_cast<int>(val);}
        if("encoder_ch1_1"==(*i)->name){encoder_ch1_1 = boost::any_cast<int>(val);}
        if("encoder_ch1_2"==(*i)->name){encoder_ch1_2 = boost::any_cast<int>(val);}
        if("encoder_ch1_3"==(*i)->name){encoder_ch1_3 = boost::any_cast<int>(val);}
      }
    }

    bool publish_flag;
bool drive_flag;
int drive_mode;
bool drive_id_0;
bool drive_id_1;
bool drive_id_2;
bool drive_id_3;
double each_vel_0;
double each_vel_1;
double each_vel_2;
double each_vel_3;
double each_ang_0;
double each_ang_1;
double each_ang_2;
double each_ang_3;
double all_vel;
double all_ang;
bool gain_flag;
bool gain_id_ch0_0;
bool gain_id_ch0_1;
bool gain_id_ch0_2;
bool gain_id_ch0_3;
int gain_ch0_0;
int gain_ch0_1;
int gain_ch0_2;
int gain_ch0_3;
bool gain_id_ch1_0;
bool gain_id_ch1_1;
bool gain_id_ch1_2;
bool gain_id_ch1_3;
int gain_ch1_0;
int gain_ch1_1;
int gain_ch1_2;
int gain_ch1_3;
bool encoder_flag;
bool encoder_id_ch0_0;
bool encoder_id_ch0_1;
bool encoder_id_ch0_2;
bool encoder_id_ch0_3;
int encoder_ch0_0;
int encoder_ch0_1;
int encoder_ch0_2;
int encoder_ch0_3;
bool encoder_id_ch1_0;
bool encoder_id_ch1_1;
bool encoder_id_ch1_2;
bool encoder_id_ch1_3;
int encoder_ch1_0;
int encoder_ch1_1;
int encoder_ch1_2;
int encoder_ch1_3;

    bool state;
    std::string name;

    
}groups;



//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool publish_flag;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool drive_flag;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int drive_mode;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool drive_id_0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool drive_id_1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool drive_id_2;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool drive_id_3;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double each_vel_0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double each_vel_1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double each_vel_2;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double each_vel_3;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double each_ang_0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double each_ang_1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double each_ang_2;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double each_ang_3;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double all_vel;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double all_ang;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool gain_flag;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool gain_id_ch0_0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool gain_id_ch0_1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool gain_id_ch0_2;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool gain_id_ch0_3;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int gain_ch0_0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int gain_ch0_1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int gain_ch0_2;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int gain_ch0_3;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool gain_id_ch1_0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool gain_id_ch1_1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool gain_id_ch1_2;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool gain_id_ch1_3;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int gain_ch1_0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int gain_ch1_1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int gain_ch1_2;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int gain_ch1_3;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool encoder_flag;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool encoder_id_ch0_0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool encoder_id_ch0_1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool encoder_id_ch0_2;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool encoder_id_ch0_3;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int encoder_ch0_0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int encoder_ch0_1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int encoder_ch0_2;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int encoder_ch0_3;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool encoder_id_ch1_0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool encoder_id_ch1_1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool encoder_id_ch1_2;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool encoder_id_ch1_3;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int encoder_ch1_0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int encoder_ch1_1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int encoder_ch1_2;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int encoder_ch1_3;
//#line 255 "/opt/ros/groovy/share/dynamic_reconfigure/templates/ConfigType.h"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("CartCommandConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const CartCommandConfig &__max__ = __getMax__();
      const CartCommandConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const CartCommandConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const CartCommandConfig &__getDefault__();
    static const CartCommandConfig &__getMax__();
    static const CartCommandConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const CartCommandConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void CartCommandConfig::ParamDescription<std::string>::clamp(CartCommandConfig &config, const CartCommandConfig &max, const CartCommandConfig &min) const
  {
    return;
  }

  class CartCommandConfigStatics
  {
    friend class CartCommandConfig;
    
    CartCommandConfigStatics()
    {
CartCommandConfig::GroupDescription<CartCommandConfig::DEFAULT, CartCommandConfig> Default("Default", "", 0, 0, true, &CartCommandConfig::groups);
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.publish_flag = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.publish_flag = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.publish_flag = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("publish_flag", "bool", 0, "Switch for publishing the message", "", &CartCommandConfig::publish_flag)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("publish_flag", "bool", 0, "Switch for publishing the message", "", &CartCommandConfig::publish_flag)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.drive_flag = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.drive_flag = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.drive_flag = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("drive_flag", "bool", 0, "drive flag", "", &CartCommandConfig::drive_flag)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("drive_flag", "bool", 0, "drive flag", "", &CartCommandConfig::drive_flag)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.drive_mode = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.drive_mode = 4;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.drive_mode = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<int>("drive_mode", "int", 0, "driving mode", "{'enum_description': 'An enum to set the driving mode.', 'enum': [{'srcline': 19, 'description': 'STOP MODE', 'srcfile': '../cfg/CartCommand.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'STOP_MODE'}, {'srcline': 20, 'description': 'TURN MODE', 'srcfile': '../cfg/CartCommand.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'TURN_MODE'}, {'srcline': 21, 'description': 'DRIVE MODE', 'srcfile': '../cfg/CartCommand.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'DRIVE_MODE'}, {'srcline': 22, 'description': 'MANUAL MODE', 'srcfile': '../cfg/CartCommand.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'MANUAL_MODE'}, {'srcline': 23, 'description': 'RESTART MODE', 'srcfile': '../cfg/CartCommand.cfg', 'cconsttype': 'const int', 'value': 4, 'ctype': 'int', 'type': 'int', 'name': 'RESTART_MODE'}]}", &CartCommandConfig::drive_mode)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<int>("drive_mode", "int", 0, "driving mode", "{'enum_description': 'An enum to set the driving mode.', 'enum': [{'srcline': 19, 'description': 'STOP MODE', 'srcfile': '../cfg/CartCommand.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'STOP_MODE'}, {'srcline': 20, 'description': 'TURN MODE', 'srcfile': '../cfg/CartCommand.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'TURN_MODE'}, {'srcline': 21, 'description': 'DRIVE MODE', 'srcfile': '../cfg/CartCommand.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'DRIVE_MODE'}, {'srcline': 22, 'description': 'MANUAL MODE', 'srcfile': '../cfg/CartCommand.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'MANUAL_MODE'}, {'srcline': 23, 'description': 'RESTART MODE', 'srcfile': '../cfg/CartCommand.cfg', 'cconsttype': 'const int', 'value': 4, 'ctype': 'int', 'type': 'int', 'name': 'RESTART_MODE'}]}", &CartCommandConfig::drive_mode)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.drive_id_0 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.drive_id_0 = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.drive_id_0 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("drive_id_0", "bool", 0, "Activate left front wheel", "", &CartCommandConfig::drive_id_0)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("drive_id_0", "bool", 0, "Activate left front wheel", "", &CartCommandConfig::drive_id_0)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.drive_id_1 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.drive_id_1 = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.drive_id_1 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("drive_id_1", "bool", 0, "Activate left back wheel", "", &CartCommandConfig::drive_id_1)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("drive_id_1", "bool", 0, "Activate left back wheel", "", &CartCommandConfig::drive_id_1)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.drive_id_2 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.drive_id_2 = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.drive_id_2 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("drive_id_2", "bool", 0, "Activate right back wheel", "", &CartCommandConfig::drive_id_2)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("drive_id_2", "bool", 0, "Activate right back wheel", "", &CartCommandConfig::drive_id_2)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.drive_id_3 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.drive_id_3 = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.drive_id_3 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("drive_id_3", "bool", 0, "Activate right front wheel", "", &CartCommandConfig::drive_id_3)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("drive_id_3", "bool", 0, "Activate right front wheel", "", &CartCommandConfig::drive_id_3)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.each_vel_0 = -20.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.each_vel_0 = 20.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.each_vel_0 = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<double>("each_vel_0", "double", 0, "velocity of left front wheel [mm/s] (MANUAL_MODE)", "", &CartCommandConfig::each_vel_0)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<double>("each_vel_0", "double", 0, "velocity of left front wheel [mm/s] (MANUAL_MODE)", "", &CartCommandConfig::each_vel_0)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.each_vel_1 = -20.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.each_vel_1 = 20.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.each_vel_1 = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<double>("each_vel_1", "double", 0, "velocity of left back wheel [mm/s] (MANUAL_MODE)", "", &CartCommandConfig::each_vel_1)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<double>("each_vel_1", "double", 0, "velocity of left back wheel [mm/s] (MANUAL_MODE)", "", &CartCommandConfig::each_vel_1)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.each_vel_2 = -20.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.each_vel_2 = 20.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.each_vel_2 = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<double>("each_vel_2", "double", 0, "velocity of right back wheel [mm/s] (MANUAL_MODE)", "", &CartCommandConfig::each_vel_2)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<double>("each_vel_2", "double", 0, "velocity of right back wheel [mm/s] (MANUAL_MODE)", "", &CartCommandConfig::each_vel_2)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.each_vel_3 = -20.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.each_vel_3 = 20.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.each_vel_3 = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<double>("each_vel_3", "double", 0, "velocity of right front wheel [mm/s] (MANUAL_MODE)", "", &CartCommandConfig::each_vel_3)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<double>("each_vel_3", "double", 0, "velocity of right front wheel [mm/s] (MANUAL_MODE)", "", &CartCommandConfig::each_vel_3)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.each_ang_0 = -180.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.each_ang_0 = 180.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.each_ang_0 = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<double>("each_ang_0", "double", 0, "steering angle of left front wheel [deg] (MANUAL_MODE)", "", &CartCommandConfig::each_ang_0)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<double>("each_ang_0", "double", 0, "steering angle of left front wheel [deg] (MANUAL_MODE)", "", &CartCommandConfig::each_ang_0)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.each_ang_1 = -180.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.each_ang_1 = 180.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.each_ang_1 = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<double>("each_ang_1", "double", 0, "steering angle of left back wheel [deg] (MANUAL_MODE)", "", &CartCommandConfig::each_ang_1)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<double>("each_ang_1", "double", 0, "steering angle of left back wheel [deg] (MANUAL_MODE)", "", &CartCommandConfig::each_ang_1)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.each_ang_2 = -180.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.each_ang_2 = 180.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.each_ang_2 = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<double>("each_ang_2", "double", 0, "steering angle of right back wheel [deg] (MANUAL_MODE)", "", &CartCommandConfig::each_ang_2)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<double>("each_ang_2", "double", 0, "steering angle of right back wheel [deg] (MANUAL_MODE)", "", &CartCommandConfig::each_ang_2)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.each_ang_3 = -180.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.each_ang_3 = 180.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.each_ang_3 = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<double>("each_ang_3", "double", 0, "steering angle of right front wheel [deg] (MANUAL_MODE)", "", &CartCommandConfig::each_ang_3)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<double>("each_ang_3", "double", 0, "steering angle of right front wheel [deg] (MANUAL_MODE)", "", &CartCommandConfig::each_ang_3)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.all_vel = -50.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.all_vel = 50.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.all_vel = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<double>("all_vel", "double", 0, "velocity of left front wheel [mm/s]", "", &CartCommandConfig::all_vel)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<double>("all_vel", "double", 0, "velocity of left front wheel [mm/s]", "", &CartCommandConfig::all_vel)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.all_ang = -180.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.all_ang = 180.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.all_ang = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<double>("all_ang", "double", 0, "steering angle of left front wheel [deg]", "", &CartCommandConfig::all_ang)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<double>("all_ang", "double", 0, "steering angle of left front wheel [deg]", "", &CartCommandConfig::all_ang)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.gain_flag = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.gain_flag = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.gain_flag = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("gain_flag", "bool", 0, "gain flag", "", &CartCommandConfig::gain_flag)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("gain_flag", "bool", 0, "gain flag", "", &CartCommandConfig::gain_flag)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.gain_id_ch0_0 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.gain_id_ch0_0 = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.gain_id_ch0_0 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("gain_id_ch0_0", "bool", 0, "Activate gain change of left front driving wheel", "", &CartCommandConfig::gain_id_ch0_0)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("gain_id_ch0_0", "bool", 0, "Activate gain change of left front driving wheel", "", &CartCommandConfig::gain_id_ch0_0)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.gain_id_ch0_1 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.gain_id_ch0_1 = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.gain_id_ch0_1 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("gain_id_ch0_1", "bool", 0, "Activate gain change of left back driving wheel", "", &CartCommandConfig::gain_id_ch0_1)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("gain_id_ch0_1", "bool", 0, "Activate gain change of left back driving wheel", "", &CartCommandConfig::gain_id_ch0_1)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.gain_id_ch0_2 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.gain_id_ch0_2 = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.gain_id_ch0_2 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("gain_id_ch0_2", "bool", 0, "Activate gain change of right back driving wheel", "", &CartCommandConfig::gain_id_ch0_2)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("gain_id_ch0_2", "bool", 0, "Activate gain change of right back driving wheel", "", &CartCommandConfig::gain_id_ch0_2)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.gain_id_ch0_3 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.gain_id_ch0_3 = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.gain_id_ch0_3 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("gain_id_ch0_3", "bool", 0, "Activate gain change of right front driving wheel", "", &CartCommandConfig::gain_id_ch0_3)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("gain_id_ch0_3", "bool", 0, "Activate gain change of right front driving wheel", "", &CartCommandConfig::gain_id_ch0_3)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.gain_ch0_0 = -32768;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.gain_ch0_0 = 32767;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.gain_ch0_0 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<int>("gain_ch0_0", "int", 0, "gain of left front driving wheel", "", &CartCommandConfig::gain_ch0_0)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<int>("gain_ch0_0", "int", 0, "gain of left front driving wheel", "", &CartCommandConfig::gain_ch0_0)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.gain_ch0_1 = -32768;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.gain_ch0_1 = 32767;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.gain_ch0_1 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<int>("gain_ch0_1", "int", 0, "gain of left back driving wheel", "", &CartCommandConfig::gain_ch0_1)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<int>("gain_ch0_1", "int", 0, "gain of left back driving wheel", "", &CartCommandConfig::gain_ch0_1)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.gain_ch0_2 = -32768;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.gain_ch0_2 = 32767;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.gain_ch0_2 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<int>("gain_ch0_2", "int", 0, "gain of right back driving wheel", "", &CartCommandConfig::gain_ch0_2)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<int>("gain_ch0_2", "int", 0, "gain of right back driving wheel", "", &CartCommandConfig::gain_ch0_2)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.gain_ch0_3 = -32768;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.gain_ch0_3 = 32767;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.gain_ch0_3 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<int>("gain_ch0_3", "int", 0, "gain of right front driving wheel", "", &CartCommandConfig::gain_ch0_3)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<int>("gain_ch0_3", "int", 0, "gain of right front driving wheel", "", &CartCommandConfig::gain_ch0_3)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.gain_id_ch1_0 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.gain_id_ch1_0 = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.gain_id_ch1_0 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("gain_id_ch1_0", "bool", 0, "Activate gain change of left front steering motor", "", &CartCommandConfig::gain_id_ch1_0)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("gain_id_ch1_0", "bool", 0, "Activate gain change of left front steering motor", "", &CartCommandConfig::gain_id_ch1_0)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.gain_id_ch1_1 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.gain_id_ch1_1 = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.gain_id_ch1_1 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("gain_id_ch1_1", "bool", 0, "Activate gain change of left back steering motor", "", &CartCommandConfig::gain_id_ch1_1)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("gain_id_ch1_1", "bool", 0, "Activate gain change of left back steering motor", "", &CartCommandConfig::gain_id_ch1_1)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.gain_id_ch1_2 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.gain_id_ch1_2 = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.gain_id_ch1_2 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("gain_id_ch1_2", "bool", 0, "Activate gain change of right back steering motor", "", &CartCommandConfig::gain_id_ch1_2)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("gain_id_ch1_2", "bool", 0, "Activate gain change of right back steering motor", "", &CartCommandConfig::gain_id_ch1_2)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.gain_id_ch1_3 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.gain_id_ch1_3 = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.gain_id_ch1_3 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("gain_id_ch1_3", "bool", 0, "Activate gain change of right front steering motor", "", &CartCommandConfig::gain_id_ch1_3)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("gain_id_ch1_3", "bool", 0, "Activate gain change of right front steering motor", "", &CartCommandConfig::gain_id_ch1_3)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.gain_ch1_0 = -32768;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.gain_ch1_0 = 32767;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.gain_ch1_0 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<int>("gain_ch1_0", "int", 0, "gain of left front steering motor", "", &CartCommandConfig::gain_ch1_0)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<int>("gain_ch1_0", "int", 0, "gain of left front steering motor", "", &CartCommandConfig::gain_ch1_0)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.gain_ch1_1 = -32768;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.gain_ch1_1 = 32767;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.gain_ch1_1 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<int>("gain_ch1_1", "int", 0, "gain of left back steering motor", "", &CartCommandConfig::gain_ch1_1)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<int>("gain_ch1_1", "int", 0, "gain of left back steering motor", "", &CartCommandConfig::gain_ch1_1)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.gain_ch1_2 = -32768;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.gain_ch1_2 = 32767;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.gain_ch1_2 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<int>("gain_ch1_2", "int", 0, "gain of right back steering motor", "", &CartCommandConfig::gain_ch1_2)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<int>("gain_ch1_2", "int", 0, "gain of right back steering motor", "", &CartCommandConfig::gain_ch1_2)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.gain_ch1_3 = -32768;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.gain_ch1_3 = 32767;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.gain_ch1_3 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<int>("gain_ch1_3", "int", 0, "gain of right front steering motor", "", &CartCommandConfig::gain_ch1_3)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<int>("gain_ch1_3", "int", 0, "gain of right front steering motor", "", &CartCommandConfig::gain_ch1_3)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.encoder_flag = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.encoder_flag = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.encoder_flag = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("encoder_flag", "bool", 0, "encoder flag", "", &CartCommandConfig::encoder_flag)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("encoder_flag", "bool", 0, "encoder flag", "", &CartCommandConfig::encoder_flag)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.encoder_id_ch0_0 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.encoder_id_ch0_0 = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.encoder_id_ch0_0 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("encoder_id_ch0_0", "bool", 0, "Activate encoder reset of left front driving wheel", "", &CartCommandConfig::encoder_id_ch0_0)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("encoder_id_ch0_0", "bool", 0, "Activate encoder reset of left front driving wheel", "", &CartCommandConfig::encoder_id_ch0_0)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.encoder_id_ch0_1 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.encoder_id_ch0_1 = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.encoder_id_ch0_1 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("encoder_id_ch0_1", "bool", 0, "Activate encoder reset of left back driving wheel", "", &CartCommandConfig::encoder_id_ch0_1)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("encoder_id_ch0_1", "bool", 0, "Activate encoder reset of left back driving wheel", "", &CartCommandConfig::encoder_id_ch0_1)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.encoder_id_ch0_2 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.encoder_id_ch0_2 = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.encoder_id_ch0_2 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("encoder_id_ch0_2", "bool", 0, "Activate encoder reset of right back driving wheel", "", &CartCommandConfig::encoder_id_ch0_2)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("encoder_id_ch0_2", "bool", 0, "Activate encoder reset of right back driving wheel", "", &CartCommandConfig::encoder_id_ch0_2)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.encoder_id_ch0_3 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.encoder_id_ch0_3 = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.encoder_id_ch0_3 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("encoder_id_ch0_3", "bool", 0, "Activate encoder reset of right front driving wheel", "", &CartCommandConfig::encoder_id_ch0_3)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("encoder_id_ch0_3", "bool", 0, "Activate encoder reset of right front driving wheel", "", &CartCommandConfig::encoder_id_ch0_3)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.encoder_ch0_0 = -32768;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.encoder_ch0_0 = 32767;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.encoder_ch0_0 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<int>("encoder_ch0_0", "int", 0, "encoder value of left front driving wheel", "", &CartCommandConfig::encoder_ch0_0)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<int>("encoder_ch0_0", "int", 0, "encoder value of left front driving wheel", "", &CartCommandConfig::encoder_ch0_0)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.encoder_ch0_1 = -32768;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.encoder_ch0_1 = 32767;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.encoder_ch0_1 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<int>("encoder_ch0_1", "int", 0, "encoder value of left back driving wheel", "", &CartCommandConfig::encoder_ch0_1)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<int>("encoder_ch0_1", "int", 0, "encoder value of left back driving wheel", "", &CartCommandConfig::encoder_ch0_1)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.encoder_ch0_2 = -32768;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.encoder_ch0_2 = 32767;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.encoder_ch0_2 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<int>("encoder_ch0_2", "int", 0, "encoder value of right back driving wheel", "", &CartCommandConfig::encoder_ch0_2)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<int>("encoder_ch0_2", "int", 0, "encoder value of right back driving wheel", "", &CartCommandConfig::encoder_ch0_2)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.encoder_ch0_3 = -32768;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.encoder_ch0_3 = 32767;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.encoder_ch0_3 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<int>("encoder_ch0_3", "int", 0, "encoder value of right front driving wheel", "", &CartCommandConfig::encoder_ch0_3)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<int>("encoder_ch0_3", "int", 0, "encoder value of right front driving wheel", "", &CartCommandConfig::encoder_ch0_3)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.encoder_id_ch1_0 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.encoder_id_ch1_0 = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.encoder_id_ch1_0 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("encoder_id_ch1_0", "bool", 0, "Activate encoder reset of left front steering motor", "", &CartCommandConfig::encoder_id_ch1_0)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("encoder_id_ch1_0", "bool", 0, "Activate encoder reset of left front steering motor", "", &CartCommandConfig::encoder_id_ch1_0)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.encoder_id_ch1_1 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.encoder_id_ch1_1 = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.encoder_id_ch1_1 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("encoder_id_ch1_1", "bool", 0, "Activate encoder reset of left back steering motor", "", &CartCommandConfig::encoder_id_ch1_1)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("encoder_id_ch1_1", "bool", 0, "Activate encoder reset of left back steering motor", "", &CartCommandConfig::encoder_id_ch1_1)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.encoder_id_ch1_2 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.encoder_id_ch1_2 = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.encoder_id_ch1_2 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("encoder_id_ch1_2", "bool", 0, "Activate encoder reset of right back steering motor", "", &CartCommandConfig::encoder_id_ch1_2)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("encoder_id_ch1_2", "bool", 0, "Activate encoder reset of right back steering motor", "", &CartCommandConfig::encoder_id_ch1_2)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.encoder_id_ch1_3 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.encoder_id_ch1_3 = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.encoder_id_ch1_3 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("encoder_id_ch1_3", "bool", 0, "Activate encoder reset of right front steering motor", "", &CartCommandConfig::encoder_id_ch1_3)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<bool>("encoder_id_ch1_3", "bool", 0, "Activate encoder reset of right front steering motor", "", &CartCommandConfig::encoder_id_ch1_3)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.encoder_ch1_0 = -32768;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.encoder_ch1_0 = 32767;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.encoder_ch1_0 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<int>("encoder_ch1_0", "int", 0, "encoder value of left front steering motor", "", &CartCommandConfig::encoder_ch1_0)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<int>("encoder_ch1_0", "int", 0, "encoder value of left front steering motor", "", &CartCommandConfig::encoder_ch1_0)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.encoder_ch1_1 = -32768;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.encoder_ch1_1 = 32767;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.encoder_ch1_1 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<int>("encoder_ch1_1", "int", 0, "encoder value of left back steering motor", "", &CartCommandConfig::encoder_ch1_1)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<int>("encoder_ch1_1", "int", 0, "encoder value of left back steering motor", "", &CartCommandConfig::encoder_ch1_1)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.encoder_ch1_2 = -32768;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.encoder_ch1_2 = 32767;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.encoder_ch1_2 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<int>("encoder_ch1_2", "int", 0, "encoder value of right back steering motor", "", &CartCommandConfig::encoder_ch1_2)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<int>("encoder_ch1_2", "int", 0, "encoder value of right back steering motor", "", &CartCommandConfig::encoder_ch1_2)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.encoder_ch1_3 = -32768;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.encoder_ch1_3 = 32767;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.encoder_ch1_3 = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<int>("encoder_ch1_3", "int", 0, "encoder value of right front steering motor", "", &CartCommandConfig::encoder_ch1_3)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(CartCommandConfig::AbstractParamDescriptionConstPtr(new CartCommandConfig::ParamDescription<int>("encoder_ch1_3", "int", 0, "encoder value of right front steering motor", "", &CartCommandConfig::encoder_ch1_3)));
//#line 233 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.convertParams();
//#line 233 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(CartCommandConfig::AbstractGroupDescriptionConstPtr(new CartCommandConfig::GroupDescription<CartCommandConfig::DEFAULT, CartCommandConfig>(Default)));
//#line 390 "/opt/ros/groovy/share/dynamic_reconfigure/templates/ConfigType.h"
    
      for (std::vector<CartCommandConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<CartCommandConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<CartCommandConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    CartCommandConfig __max__;
    CartCommandConfig __min__;
    CartCommandConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const CartCommandConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static CartCommandConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &CartCommandConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const CartCommandConfig &CartCommandConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const CartCommandConfig &CartCommandConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const CartCommandConfig &CartCommandConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<CartCommandConfig::AbstractParamDescriptionConstPtr> &CartCommandConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<CartCommandConfig::AbstractGroupDescriptionConstPtr> &CartCommandConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const CartCommandConfigStatics *CartCommandConfig::__get_statics__()
  {
    const static CartCommandConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = CartCommandConfigStatics::get_instance();
    
    return statics;
  }

//#line 19 "../cfg/CartCommand.cfg"
      const int CartCommand_STOP_MODE = 0;
//#line 20 "../cfg/CartCommand.cfg"
      const int CartCommand_TURN_MODE = 1;
//#line 21 "../cfg/CartCommand.cfg"
      const int CartCommand_DRIVE_MODE = 2;
//#line 22 "../cfg/CartCommand.cfg"
      const int CartCommand_MANUAL_MODE = 3;
//#line 23 "../cfg/CartCommand.cfg"
      const int CartCommand_RESTART_MODE = 4;
}

#endif // __CARTCOMMANDRECONFIGURATOR_H__
