(cl:in-package hearbo_cart_msgs-msg)
(cl:export '(DRIVE_FLAG-VAL
          DRIVE_FLAG
          GAIN_FLAG-VAL
          GAIN_FLAG
          ENCODER_FLAG-VAL
          ENCODER_FLAG
          DRIVE_MODE-VAL
          DRIVE_MODE
          DRIVE_ID-VAL
          DRIVE_ID
          EACH_VEL-VAL
          EACH_VEL
          EACH_ANG-VAL
          EACH_ANG
          ALL_VEL-VAL
          ALL_VEL
          ALL_ANG-VAL
          ALL_ANG
          GAIN_ID_CH0-VAL
          GAIN_ID_CH0
          GAIN_ID_CH1-VAL
          GAIN_ID_CH1
          GAIN_CH0-VAL
          GAIN_CH0
          GAIN_CH1-VAL
          GAIN_CH1
          ENCODER_ID_CH0-VAL
          ENCODER_ID_CH0
          ENCODER_ID_CH1-VAL
          ENCODER_ID_CH1
          ENCODER_CH0-VAL
          ENCODER_CH0
          ENCODER_CH1-VAL
          ENCODER_CH1
))